services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 30s

    volumes:
      - ./api:/app/api

    command: ["uvicorn", "api.fast:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

    environment:
      - DB_URL=postgresql://postgres:postgres123@db:5432/postgres
    networks:
      - backend
    depends_on:
    - db


  db:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=postgres123
    networks:
      - backend



networks:
  backend:
    driver: bridge
