services:
    metabase:
      image: metabase/metabase
      restart: always
      volumes:
        - ./metabase-data:/metabase-data
      environment:
       - MB_DB_FILE=/metabase-data/metabase.db
      ports:
        - 3000:3000
      # depends_on:
      #   - database
