apiVersion: v1
kind: Service
metadata:
  name: counter
spec:
  selector:
    app: counter
  type: LoadBalancer
  ports:
  - name: service-port
    protocol: TCP
    port: 5000
    targetPort: counter-port
